# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a89d6e1c54b3d79c7abaa5c6ada2fe0b02df553ef8f659c4797511cc3e5a407924d085470845f7a8e02582d928b7f497c83f378ccdab382b48194f4a93326ab2

test:
  secret_key_base: 4569d6acdb5823fa9fe38ffe65048908d1d23543d7bff46a28ba414078b6e7df9a52367ffcf3ee9229453b2564f7159fd85078b7fca7c670be8a4a39901031d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
